### ISSUE TITLE
spirv_cross::Resource contains wrong name 

### ISSUE THREAD

**Issue by andrejnau** [KhronosGroup/SPIRV-Cross#1018]
I had problem that spirv_cross::Resource had the same name for different resources.
I found workaround: compiler.get_name(resource.id), but it still looks like bug.

[Shader code](https://github.com/andrejnau/FlyCube/blob/99f015f8b3ad86c9ec57c28cb61f91117fc11918/assets/shaders/SponzaPbr/Skinning_CS.hlsl) and compiler command line:
```glslangValidator --auto-map-bindings  --hlsl-iomap  -g  -e main -S comp -V  -D  -fhlsl_functionality1 Skinning_CS.hlsl -o some_path```

Also it affects on json Reflection [http://shader-playground.timjones.io/6d0cfa1359806c6b6a40fa5e67114035](http://shader-playground.timjones.io/6d0cfa1359806c6b6a40fa5e67114035) (change Output to Reflection). This json has 4 resources named "index buffer".

**Comment by HansKristian-Work** [comment]
This is a known issue, and I think I'll add a workaround. This is actually a quirk with how blocks and instance names are declared and there is some ambiguity. When declaring a buffer in GLSL, there's generally two names to consider:

```
layout(...) buffer BlockName <- the type: GLSL wants this
{
} instance_name; <- HLSL wants this
```

In GLSL, the BlockName is the significant name, and that's the name which carries some kind of meaning in GL, however, with HLSL, it's the instance_name which carries the name, the block type is reused across multiple buffers, and there is no obvious way for SPIRV-Cross to know which style to consider. It might be possible to look at OpSource HLSL and choose based on that, but that might be stripped away since it's a debug opcode. Another way might be to heuristically detect this if multiple blocks refer to the same type and choose implementation based on that ...

**Comment by HansKristian-Work** [comment]
Updated Wiki: https://github.com/KhronosGroup/SPIRV-Cross/wiki/Reflection-API-user-guide#a-note-on-names
