### ISSUE TITLE
MSL: GLSL texture binding point is not converted correctly

### ISSUE THREAD

**Issue by kakashidinho** [KhronosGroup/SPIRV-Cross#1142]
I tried to covert GLSL using glsl to spirv then covert to Metal. It seems that the conversion doesn't conform to the texture binding points in glsl source.
For example, this is the source GLSL, `uTex2` bound to index 0:
```
#version 310 es

precision highp float;

layout(location=1) in vec2 texcoords;
layout(location=1) out vec4 oColor;

layout(binding=0) uniform  sampler2D uTex2;
layout(binding=1) uniform  sampler2D uTex;

void main()
{
	oColor = texture(uTex, texcoords) + texture(uTex2, texcoords);
}
```

This is the Metal output,  `uTex2` bound to index 1:
```
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct main0_out
{
    float4 oColor [[color(1)]];
};

struct main0_in
{
    float2 texcoords [[user(locn1)]];
};

fragment main0_out main0(main0_in in [[stage_in]],
                         texture2d<float> uTex [[texture(0)]],
                         texture2d<float> uTex2 [[texture(1)]],
                         sampler uTexSmplr [[sampler(0)]],
                         sampler uTex2Smplr [[sampler(1)]])
{
    main0_out out = {};
    out.oColor = uTex.sample(uTexSmplr, in.texcoords) + uTex2.sample(uTex2Smplr, in.texcoords);
    return out;
}
```

Is it expected? Also I'm new to SPIRV-cross. Is there any way to retrieved the converted index of textures, as well as the name of converted entry point (main0)?
I looked into the Reflection guide on the wiki page. However, it seems like it only supports querying the info before the conversion.

**Comment by HansKristian-Work** [comment]
When converting from SPIR-V to MSL, bindings are automatically generated. This is because the SPIR-V binding model does not match MSL's binding model and cannot be translated 1:1. The way to go if you need a user-defined remapping scheme is to use add_msl_resource_binding in the API. https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_msl.hpp#L324.

Alternatively, if you can deal with the auto-remapping, you can use get_automatic_resource_binding() to get the MSL binding. https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_msl.hpp#L346.

**Comment by HansKristian-Work** [comment]
There is an MSL option (enable_decoration_binding) now which maps bindings directly to ids for convenience, assuming all the stars align. This maps to the older binding behavior in SPIRV-Cross if it is desirable.
