### ISSUE TITLE
Comment annotations

### ISSUE THREAD

**Issue by VelocityRa** [KhronosGroup/SPIRV-Cross#1158]
I work with emulators, and and when making shader (re)compilers that translate guest shader assembly to SPIR-V -> GLSL, it's quite handy to be able to annotate the resulting GLSL with a comment with the original shader disassembly before emitting the equivalent SPIR-V that emulates it.

At the moment projects like decaf-emu, resort to [post-processing the GLSL string](https://github.com/decaf-emu/decaf-emu/blob/61b17b110478bc01d19ecd698c3b6747544a5e04/src/libgpu/src/spirv/spirv_transpiler.cpp#L775), which is obviously less than ideal.

I imagine that's hardly the only use case for something like this, surely other kinds of projects could benefit too from comments at arbitrary points in the instruction stream.

Maybe `OpLine` or something can be used/repurposed for this? It could be optional.

Thank you.

**Comment by HansKristian-Work** [comment]
The code you linked to post-processed SPIRV-Tools disasm though, not SPIRV-Cross output.

I suppose it's possible to add a mode where the OpLine file is treated as a comment, so rather than emitting

```
#line 0 "// This is my comment"
```
you'd get just
```
// This is my comment
```

This only works for comments directly tied to source. Adding comments on global resource declaration isn't really possible with OpLine.

**Comment by VelocityRa** [comment]
Oh, the option `emit_line_directives ` that you mentioned suits my needs (even if it can't be used on global resources).
I wasn't aware it was implemented, thanks!
