### ISSUE TITLE
Gives 0 for struct offset and 0 for member offset, when layout(offset=16).

### ISSUE THREAD

**Issue by cheako** [KhronosGroup/SPIRV-Cross#1176]
https://gitlab.com/cheako/hazel-rs/blob/4a3e99a21a3106be475e3583755efe64ef67a770/assets/shaders/flat_color.glsl

The idea is that push constants for each stage need to be separated.
https://gitlab.com/cheako/hazel-rs/blob/47516da6a669db05b574b089c20f08066518f4cd/src/renderer/pipeline.rs#L392

I tried adding the offsets together, but if they are always 0 there is nothing to do.

I planned to use the offset to index a hashmap that kept track of the shaderstageflags.

Edit: push_constant_ranges is separate from type_data_by_name, because it USED to cover the struct not the members, that's something both new to attempt to deal with the issue here AND most probably wrong.

**Comment by HansKristian-Work** [comment]
I'm not really sure what the problem is.

Calling Offset decoration on a resource.id is not what you're supposed to do. You can call get_member_decoration on (resource.base_type_id) if you want to extract the Offset decoration from the block.

get_active_buffer_ranges() is probably what you want to look at though, it's designed to pull out push constant ranges like this. see https://github.com/KhronosGroup/SPIRV-Cross/blob/master/main.cpp#L418

**Comment by cheako** [comment]
@HansKristian-Work Thanks, I'll look into adding it.

**Comment by cheako** [comment]
get_active_buffer_ranges() isn't well documented.  Specifically "range" member is ambiguous, should it just be size or length?

**Comment by HansKristian-Work** [comment]
It's size (in bytes). It was supposed to match VkPushConstantRange, but I see now it uses "size", must have been an oversight.

**Comment by cheako** [comment]
Thanks, it's working.
