### ISSUE TITLE
Support tesselation, geometry and compute shaders in HLSL backend

### ISSUE THREAD

**Issue by oscarbg** [KhronosGroup/SPIRV-Cross#121]
Just pointing it out,
I know also that this backend is experimental and currently seems to support vertex and fragment shaders..

**Comment by RobDangerous** [comment]
Tessellation is problematic because HLSL uses a separate patch function in the tes-control shader. What I did before is to feed in special GLSL shaders ala
```
#version 450

layout(vertices = 3) out;

in vec3 vPosition[];

out vec3 tcPosition[];

uniform float TessLevelInner;
uniform float TessLevelOuter;

void patch_main() {
	gl_TessLevelInner[0] = TessLevelInner;
	gl_TessLevelOuter[0] = TessLevelOuter;
	gl_TessLevelOuter[1] = TessLevelOuter;
	gl_TessLevelOuter[2] = TessLevelOuter;
}

void main() {
	tcPosition[gl_InvocationID] = vPosition[gl_InvocationID];
}
```
this translates trivially to HLSL and for the actual GLSL output I combined both functions. But I'm pretty sure that's not wanted here. @HansKristian-ARM do you think it's viable to translate the tessellation-control function twice while marking different variables as unused, then trying to optimize? It sounds like a lot of work and might end up flaky but it's the only idea I currently have.

**Comment by HansKristian-ARM** [comment]
Tessellation/geometry will require a lot of thinking before we start on it.
There's still ways to go before vertex/fragment backend gets mature. The next step would be compute after that, then we can consider tess/geom.

**Comment by RobDangerous** [comment]
Okidoki (didn't have major problems with geometry though).

**Comment by HansKristian-ARM** [comment]
Geometry is definitely easier than tess though, so features will probably land in order of:
- Compute
- Geom
- Tess

**Comment by crazywig** [comment]
Would be handy having geometry shader support for HLSL

**Comment by HansKristian-Work** [comment]
Outdated issue, there's an issue for geom/tess, but compute is supported since long ago.
