### ISSUE TITLE
Using Integrated Texture Coordinates in Metal, Vulkan, DirectX and OpenGL

### ISSUE THREAD

**Issue by daemyung** [KhronosGroup/SPIRV-Cross#1245]
Now my engine supports Metal, Vulkan, DirectX and OpenGL. NDC and Viewport coordinates are intergrated so all backends can make same results. However the texture coordinates couldn't be intergrated.

Texture coordinates in OpenGL is
+Y is up. Origin(0, 0) is at the bottom left corner.

Texture coordinate in Metal, Vulkan and DirectX are
+Y is down. Origin(0, 0) is at the bottom left corner.

To intergrate the texture coordinates, I can choose two options.
1. Pass the vertical flip texture matrix.
Multiply UV and VerticalFlipTextureMatrix and pass transformed UV to texture function.
Like blow...
```
mat3 VerticalFlipTextureMatrix {
   1.0, 0.0, 0.0,
   0.0, -1.0, 0.0
   0.0, 1.0, 1.0
};

vec4 texel = texture(Diffuse, (VerticalFlipTextureMatrix * UV).xy);
```

2. On OpenGL, I add some trick in glsl like below
```
#if OPEN_GL
vec4 texel = texture(Diffuse, vec2(UV.x, 1.0 - UV.y));
#else
vec4 texel = texture(Diffuse, UV);
#endif
```
However both options are not satisfied.

So I think if SPIRV-Cross support some functionality like **vertex.flip_vert_y** for the texture coordinate I can intergrate the texture coordinate to all graphics API.

Can SPIRV-CROSS support this?

**Comment by HansKristian-Work** [comment]
This is a classic misconception, and this cannot, and will not be supported by SPIRV-Cross.
Texture space on all APIs correlate with window space. Window coord (0, 0) when rendering always matches up with UV (0, 0) on all APIs. The only real difference between APIs is Clip -> Window space, and GL's backbuffer is bottom-left when scanning out the backbuffer (but otherwise it is identical to Vulkan), but UV space is not the place to attempt any fixup, it cannot work in the general case.
