### ISSUE TITLE
Resource mapping overrides for HLSL

### ISSUE THREAD

**Issue by kvark** [KhronosGroup/SPIRV-Cross#1252]
We have the mapping overrides for MSL, which allows the same descriptor to be bound to different buffer/texture/sampler IDs on the Metal side. However, the same functionality is missing from HLSL. Mapping overrides are apparently not required for DX12 due to the specifics of how descriptor heaps work there. However, there are required for DX11, which has a similar binding model to Metal.

To clarify, I want to tell SPIRV-Cross that set X binding Y should map to CBV register A, SRV register B, UAV register C, and sampler register D.

**Comment by HansKristian-Work** [comment]
Normally, it's possible to directly override the DescriptorSet and DescriptorBinding decorations, which allows free remapping. When a resource is emitted, DescriptorSet -> SM 5.1 space#, and DescriptorBinding -> r/t/s/u#. My assumption is that this is good enough for HLSL.

The only restriction with that approach is that a COMBINED_IMAGE_SAMPLER must have its image and sampler in same binding/space, but since they have different resource type, it's generally fine.

For MSL, the flat binding space in indirect argument buffers means we cannot assign one binding to a COMBINED_IMAGE_SAMPLER, so that's a case where the resource mapping API makes more sense. It's also used to deal with the myriad of aux argument buffers and how to bind them. HLSL doesn't have that problem either.

If the existing interfaces cannot work, I can consider adding a resource remapping API to HLSL as well.

**Comment by kvark** [comment]
Yes, `set_decoration()` is what we do now, and it is **not** a proper solution.

> DescriptorSet -> SM 5.1 space#, and DescriptorBinding -> r/t/s/u#. My assumption is that this is good enough for HLSL

We do *not* want the same number here for different types of descriptors. We want to control that in order to make the bindings linear (and bind all at once). It affects more than just COMBINED_XXX stuff: for storage textures and buffers, we have to bind them to both SRV and UAV registers because we don't know at the pipeline layout creation time whether a storage resource is going to be read-only or not (it feels like a more general problem/rough edge of Vulkan).

**Comment by HansKristian-Work** [comment]
Well, OK, if that interface is not cutting it I'll look into implementing a resource mapping API similar to MSL. I expect it will look something similar to MSLResourceBinding, except it'll have space/register indices for CBV, UAV, SRV, Sampler instead. Would that work?

**Comment by kvark** [comment]
Yes, that would be exactly right. Thank you!
