### ISSUE TITLE
[C API] Missing interface to modify specialization constants

### ISSUE THREAD

**Issue by prollin** [KhronosGroup/SPIRV-Cross#1258]
The ability to modify specialization constants seem to be missing from the C API.

This feature is important when targeting ESSL 300 so specialization constants provided when setting up a pipeline object can be set through reflection.

**Comment by HansKristian-Work** [comment]
Normally, SPIRV-Cross will emit `#define` based specialization constants. Rather than recompiling multiple times in SPIRV-Cross, the ideal way of doing it is to use your own `#defines` when passing code to GLSL compiler. Adding a complete specialization constant modification API is rather tedious due to the large number of entry points required to make it complete, so I'd like to make sure the current approach cannot work first.

**Comment by prollin** [comment]
@HansKristian-Work it does work and this is what I ended up doing in the time being. The only minor drawback I can think of is that it makes the output slightly less readable (adds a lot of extra noise in files with lots of constants). Probably not worth the extra compile time required in that case.
I guess the only remaining reason would be to achieve feature parity with the C++ API.

Thank you for your help. I'll let you decide if you want to close this or keep it for future enhancement.

**Comment by HansKristian-Work** [comment]
I think I will reject this then. The `#define` based method was added to avoid having to invoke SPIRV-Cross to specialize shaders to begin with, and it's the recommended method.
