### ISSUE TITLE
HLSL: Support forcing readonly storage buffers to be UAV by ID

### ISSUE THREAD

**Issue by bbernhar** [KhronosGroup/SPIRV-Cross#1368]
I'm a Chromium developer working on WebGPU. We'd like to add functionality to extend `force_storage_buffer_as_uav` to work **per binding** instead of globally (all bindings). This ensures certain storage buffers that were declared _readonly_ in the shader but have storage usage (read/write) in the pipeline state still compile (ie. SRV(ti) + ByteAddressBuffer => UAV(ui) + RWByteAddressBuffer).

The change looks fairly straightforward - store a set of bindings which `set_hlsl_force_storage_buffer_as_uav(ID)` adds and then conditionally check it where `force_storage_buffer_as_uav` is used. The client would simply call `set_hlsl_force_storage_buffer_as_uav` before compiling.

Any concerns/comments of introducing this enhancement?

**Comment by HansKristian-Work** [comment]
For raw buffers specifically, there isn't too much of a concern here. Fortunately, you cannot pass SSBOs around to functions, so munging with the type system is not a big deal. The only thing that should change is the declaration of the resource.

However, be aware that this cannot work for any type which *does* support being passed around to functions, like Buffer vs RWBuffer, Texture vs RWTexture, etc, since the function signature does not know anything about specific resources. I suspect you're going to go down this rabbit hole and figure out this approach is unimplementable. If you go that far, you'll need to add legalization passes yourself.

I earlier added readonly RWTexture -> Texture translation for WebGPU as well. Please see discussion here: https://github.com/KhronosGroup/SPIRV-Cross/issues/1286#issuecomment-594560682.

**Comment by HansKristian-Work** [comment]
Before I commit to support this, please evaluate the implications above and verify that you're not going to design yourself into a corner. SPIRV-Cross will not support legalization passes or any complicated transforms to support this kind of thing. Replacing types is easy enough, but that's about as far as this approach can go.

**Comment by bbernhar** [comment]
Thanks, @HansKristian-Work for your feedback. This would only need to support raw buffers (aka [RW]ByteAddressBuffer). I should have the PR for review soon.

**Comment by Kangz** [comment]
Thanks @HansKristian-Work for the feedback. The situation for texture is indeed more complex and something we might run into in WebGPU later down the line. We might need to disallow such "implicit promotion" for storage textures.

**Comment by HansKristian-Work** [comment]
Merged.
