### ISSUE TITLE
Invalid code generated after rolling DEPS.

### ISSUE THREAD

**Issue by dj2** [KhronosGroup/SPIRV-Cross#1458]
I'm attempting to roll the glslang, spirv-tools and spirv-headers deps (https://github.com/KhronosGroup/SPIRV-Cross/compare/master...dj2:roll-09-02?expand=1) but when I do the tests fail to generate. I receive:

```
ERROR: /var/folders/z8/flp9w9wx0vx01vh_m_gwgn900048mf/T/tmpibs7vbd8vkshader-arithmetic-8bit.nocompat.vk.frag:29: '_192' : illegal use of type 'void' 
ERROR: 1 compilation errors.  No code generated.
```

where it looks like the test has generated:

```
void _192;
void _193;
void _194;
void _195;
```

I'm not sure how/where to fix this issue.

**Comment by dj2** [comment]
It looks like it was purposeful: https://github.com/KhronosGroup/SPIRV-Tools/pull/3720

@s-perron @dneto0

**Comment by s-perron** [comment]
I know this is awkward, but it is the only way that we can inline.  What spirv-opt passes are run?  I would expect that dead code would remove the unused undef instructions.  If not, then we should fix that.

**Comment by HansKristian-Work** [comment]
Plain `-O`. It's dead code, no other code refers to the Undefs so I implemented this by simply ignoring Undef void.

**Comment by HansKristian-Work** [comment]
What can you even do with an Undef void? From the issue apparently you can CopyObject, but what then, can it meaningfully change execution? What happens if you simply elide the CopyObjects as well?

**Comment by s-perron** [comment]
I agree it cannot be manfully used.  I would like the spec to say that the void result of an OpFunctionCall cannot be used anywhere, but we have to accept all legal code as it is defined now.

We can't "simply elide the CopyObjects" while inlining because we do not have access to the def-use chains while inlining.  They would constantly be invalidated, and rebuilding all of the time would be too expensive.

`-O` should be removing the undefs.  I'll take a look at that.

**Comment by s-perron** [comment]
I've opened https://github.com/KhronosGroup/SPIRV-Tools/pull/3780, which should allows the Undefs to be removed.
