### ISSUE TITLE
Legacy GLSL: Invalid for loop syntax

### ISSUE THREAD

**Issue by DerSchmale** [KhronosGroup/SPIRV-Cross#1545]
I'm trying to use glslangValidator and SPIRV-Cross to transpile shaders for use with (amongst others) WebGL 1 (GLSL ES 2.0). However, the resulting glsl code contains for loop syntax that's not supported for this version. The initializer/condition/continue expressions can be empty, or the continue block can be an expression using the comma operator. I'm guessing this would also fail for any legacy glsl version that doesn't support dynamic loops.

Below is a test source glsl file, converted using the following commands:
```
glslangValidator test.glsl -e main -o test.spv -G -S frag
spirv-cross test.spv --output test_conv.glsl --version 200 --es
```

The test case contains an explicit use of the command operator, but it can also be introduced by glslang when not explicit in the source code (which is my real use case).

```
#version 310 es
precision highp float;

layout (constant_id = 0) const int COUNT = 16;

layout (location = 0) out vec4 fragOut;

void main()
{
	float total = 0.0;
	float someOther = 1.0;

	for (int i = 0; i < COUNT; ++i, someOther = float(i)) {
		total += someOther;
	}
	
	fragOut = vec4(total);
}
```

The following for-loop is generated:

```
mediump int i = 0;
for (; i < COUNT; i++, someOther = float(i))
{
	total += someOther;
}
```

Expected result:

```
for (mediump int i = 0; i < count; i++) 
{
	total += someOther;
	someOther = float(i);
}

```

**Comment by HansKristian-Work** [comment]
ESSL 1.0 is extremely strict here, and there isn't much I can do. The SPIR-V you give to SPIRV-Cross must be sanitized to confirm to the requirements of ESSL 1.0. It is not safe, or possible, to do this transformation in the general case. I will not implement wild hacks to make this work for a subset of possible cases.

**Comment by DerSchmale** [comment]
Understood, thanks for the update! Perhaps a warning message or something could be helpful. Looks like I'll have to dig into the glslang conf file a bit more, although this seems to be pretty experimental still.

**Comment by JasonL663** [comment]
It's worth noting that glslang may actively generate the above ESSL issue when compiling HLSL code that might otherwise directly translate to valid ESSL:
```
glslangValidator.exe -S frag -e frag -o test.spv -V -D test.hlsl
spirv-cross test.spv --output test_conv.glsl --version 200 --es
```
```
// test.hlsl
float test[16];
float frag()
{
	float accumulator = 0;
	for (int i = 0; i < 16; ++i)
		accumulator += test[i];
	return accumulator;
}
```
```
// test_conv.glsl
...
void main()
{
    highp float _67;
    _67 = 0.0;
    for (int _66 = 0; _66 < 16; _67 += _31.test[_66], _66++)
    {
    }
    gl_FragData[0] = _67;
}
```
Which will fail to compile due to the loop body being moved into the step portion of the for-loop.

This is caused by the optimization process when translating hlsl->spv which appears to partly be necessary for producing valid spv bytecode. I was able to track the issue down to the `CreateLocalMultiStoreElimPass` that gets registered in SpvTools.cpp [here](https://github.com/KhronosGroup/glslang/blob/d51d01ccfbbbaa654768ba9a7d28abd3c9fb807d/SPIRV/SpvTools.cpp#L204).

Commenting out the above line will resolve the issue with for-loops, but will produce additional syntax errors when going from spv to glsl. That said, I have had more success correcting those issues with post-processing scripts than I had trying to correct the for-loop syntax which can otherwise get quite complicated when applying the above conversions.

This probably won't be an issue for much longer since we are finally moving towards more widely adopted alternatives, but I figured I'd add some extra info here since this thread is the first result that comes up when searching for the above issue.
