### ISSUE TITLE
ByteAddressBuffers to GLSL

### ISSUE THREAD

**Issue by guy-adshir** [KhronosGroup/SPIRV-Cross#1546]
I'm new to SPIRV-Cross, so I may be missing something, but I've run into issues with ByteAddressBuffers (coming from HLSL) compiled into GLSL. Specifically, when there is more than one ByteAddressBuffer in a shader. As far as I can tell, the 'ByteAddressBuffer' is treated as the name, and so type_ByteAddressBuffer is the name of the first buffer, and the rest get aliases, like so:

`layout(binding = 2, std430) readonly buffer type_ByteAddressBuffer
{
    uint _m0[];
} positions;

layout(binding = 6, std430) readonly buffer bounds
{
    uint _m0[];
} bounds_1;`

SPIR-V looks correct according to this [link](https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#byteaddressbuffer-and-rwbyteaddressbuffer)
The main issue I have with this is that I cannot match the names between the fragment and vertex shaders. The fragment has the above ByteAddressBuffers and the vertex shader has just one (bounds) and so even though I match the binding slots, the names no longer match. 
Is this by design? what am I missing?

**Comment by HansKristian-Work** [comment]
I suggest looking into the `compiler.set_name` APIs. What you can do is calling `compiler.set_name(resource.base_type_id, "");` for the block type, and then use `compiler.set_name(resource.id, "positions")`. The block name should inherit its name from the instance name in this case I believe. I think that should give you more predictable outputs. It's generally very hard to emit sensible names that match across stages since SPIR-V doesn't care about names, and there's both block name and instance name to consider.

**Comment by guy-adshir** [comment]
Thanks. I've tried `set_name` before posting. It did not help. For now I've found that simply removing the `OpNames` for `%type.[RW]ByteAddressBuffer` does the job, and still haven't found any downsides. Still looking though.

**Comment by HansKristian-Work** [comment]
Closing as I don't think there's more to do here.
