### ISSUE TITLE
MSL: workaround lack of support for NoContraction?

### ISSUE THREAD

**Issue by js6i** [KhronosGroup/SPIRV-Cross#1665]
When going from HLSL, the `precise` modifier typically translates to `NoContraction`, which is then ignored by the MSL backend. It could do slightly better and mark vertex output position `invariant` when `NoContraction` is seen, which presumably is the most common intention.

**Comment by HansKristian-Work** [comment]
invariant position in SPIR-V is marked with DecorationInvariant, not NoContraction.

**Comment by js6i** [comment]
Yes, well, there seems to be a mismatch here. As far as I understand, HLSL uses `precise` for this purpose and it maps best to `NoContraction`, which works. I'm not sure there's a good argument that that's wrong? It breaks at the backend, so it seems to me that the backend could try to do the right thing in this case.

**Comment by js6i** [comment]
Conversely, I'd expect a HLSL backend to translate `DecorationInvariant` to `precise`.

**Comment by mabaro** [comment]
Hello!
**Context:** 
Using spirv-cross to generate code from HLSL to target both android(vulkan)/ios, we're facing divergence problems between two passes.
Vertex output position is marked as **invariant** and, in general, this seems to work fine and the vulkan spirv works without issues on android (so far).
On the other hand, the generated MSL counterpart exhibits glitches.
Checking the generated GLSL/MSL code, there are clear divergences as the MSL compiler codepath doesn't handle **DecorationNoContraction**.

**Some investigation insights:**
It seems the **precise** tag (DecorationNoContraction) is not being taken into account, at least on some bits, on the MSL side. spirv_msl::emit_instruction() does some rewritings (i.e., for OpMatrixTimesVector) which ends up on emit_op(..., forward) where **forward** ignores the DecorationNoContraction. This happens in particular when **invariant_float_math** is enabled.
The general case is redirected through the macro MSL_BFOP, which ends in emit_binary_func_op(), which doesn't handle **DecorationNoContraction**.

My first impression is that in order to make GLSL/MSL to have the "same" behavior we'd be missing handling **DecorationNoContraction** in emit_binary_func_op(), but this would introduce some changes also for GLSL, as it's currently only taken into account in emit_binary_op(). 

I'm wondering whether adding the same behavior in emit_binary_func_op/emit_binary_op() could be right/wrong regarding the specs.

On top of that, I wonder wheter propagating the **precise** behavior to all operands involved and cascading it (i.e., bottom-up) could be necessary in order to avoid this kind of divergences. Specially since **DecorationInvariant** seems to not be enough in its current state.

Cheers!

FILES:
[simple.hlsl used as source for the tests](https://github.com/user-attachments/files/17651101/simple.hlsl.txt)
[simple.glsl_cross generated GLSL](https://github.com/user-attachments/files/17651111/simple.glsl_cross.txt)
[simple.msl_cross generated MSL](https://github.com/user-attachments/files/17651112/simple.msl_cross.txt)
