### ISSUE TITLE
Wrong type is assigned to globlal variable.

### ISSUE THREAD

**Issue by syoyo** [KhronosGroup/SPIRV-Cross#17]
spirv-cross assigns wrong type for a global variable. Reproducable with the attached shader.

```
$ glslangValidator -G ao.comp -o ao.spv
$ spirv-cross ao.spv

...
layout(binding = 1) uniform writeonly image2D destTex;

Sphere sphere[3];
Ray plane;  // <-- * this should be 'Plane plane'
...
```

[ao.comp.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/286409/ao.comp.txt)

**Comment by HansKristian-ARM** [comment]
Yes, again, the code to deal "properly" with struct name aliasing is rearing its ugly head. This is because it finds Plane and Sphere to be compatible types and assumes that they are the same type.

It seems like we will need to be more careful to only consider type aliasing if the structs are the same, but Offset decorations are different.

**Comment by HansKristian-ARM** [comment]
This should be fixed on master now.

**Comment by syoyo** [comment]
Thanks! Confirmed its now fixed.
