### ISSUE TITLE
Column-major matrices -Zpc

### ISSUE THREAD

**Issue by cpt-max** [KhronosGroup/SPIRV-Cross#1702]
I would find it really useful to compile with -Zpc, as it removes the need to transpose matrices in the framework (platform independent OpenGL and DX), or even worse, in user code.

The restriction that this only works with square matrices is a bit of a show stopper though.
The corresponding comment in spirv_glsl.cpp indicates that this restriction could potentially be lifted:
```c
	// Only square row-major matrices can be converted at this time.
	// Converting non-square matrices will require defining custom GLSL function that
	// swaps matrix elements while retaining the original dimensional form of the matrix.
	const auto mbr_type = get<SPIRType>(type.member_types[index]);
	if (mbr_type.columns != mbr_type.vecsize)
		SPIRV_CROSS_THROW("Row-major matrices must be square on this platform.");
```
Would this have a negative impact on performance, or would you expect this extra function to get optimized out in the end anyway?

**Comment by HansKristian-Work** [comment]
I guess I can add fallback paths for `transpose()` similar to other backends.

**Comment by HansKristian-Work** [comment]
On looking further into this, I think there isn't that much I can do here:

- On GLSL 110 and ESSL 100, non-square matrices are not supported.
- If non-square matrices with row-major are placed in a UBO or similar, we have to rewrite the type from mat2x3 to mat3x2. This gets super screwey with the type system and there is no layout qualifier to use.
- This restriction is actually wrong for GLSL 120, since non-square matrices are indeed supported there.
- With `--flatten-ubo` the type shenanigans disappear and it should just work.

**Comment by cpt-max** [comment]
I wasn't aware that this restriction only applies to GLSL 110. I think I can live with that, so I'm closing this one.
