### ISSUE TITLE
Metal output doesn't respect binding modifier for samplers

### ISSUE THREAD

**Issue by eliasnaur** [KhronosGroup/SPIRV-Cross#1723]
```
$ cat binding.frag
#version 310 es
precision mediump float;
layout(binding = 1) uniform sampler2D cover;

layout(location = 0) out vec4 fragColor;

void main() {
	fragColor = texture(cover, vec2(0.0, 0.0));
}
$ glslangValidator -V binding.frag
binding.frag
$ spirv-cross --msl frag.spv
#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct main0_out
{
    float4 fragColor [[color(0)]];
};

fragment main0_out main0(texture2d<float> cover [[texture(0)]], sampler coverSmplr [[sampler(0)]])
{
    main0_out out = {};
    out.fragColor = cover.sample(coverSmplr, float2(0.0));
    return out;
}
```

Notice that cover is declared with `[[texture(0)]]` and `[[sampler(0)]]`; I expected `[[texture(1)]]` and `[[sampler(1)]]` to match the `binding=1` modifier in the original.

**Comment by cdavis5e** [comment]
This is by design. Because of the huge impedance mismatch between the way Vulkan and OpenGL address shader resources and the way Metal does, by default SPIRV-Cross assigns its own bindings to the generated MSL. If you want it to instead use the binding numbers in the original SPIR-V, you must enable the MSL backend option `enable_decoration_binding`. From the C binding, that's the compiler option `SPVC_COMPILER_OPTION_MSL_ENABLE_DECORATION_BINDING`; and from the command line, that's `--msl-decoration-binding`.

**Comment by eliasnaur** [comment]
Thank you very much. I did look at the `--msl-*` options but somehow missed that one.
