### ISSUE TITLE
Shader compilation failed

### ISSUE THREAD

**Issue by ikryukov** [KhronosGroup/SPIRV-Cross#1813]
Trying to compile generated shader code and got this error:
```
@"[mvk-error] VK_ERROR_INITIALIZATION_FAILED: Shader library compile failed (Error code 3):\r\n"
@"Compilation failed: \r\n"
@"\r\n"
@"program_source:378:27: error: as_type cast from 'long' to 'float' is not allowed\r\n"
@"            float _1181 = as_type<float>((as_type<int>((_1172.x + _1172.y) + _1172.z) & (-2147483648)) | 1065353216);\r\n"
@"                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\r\n"
```
Original bug: https://github.com/KhronosGroup/MoltenVK/issues/1476

**Comment by cdavis5e** [comment]
It's the classic `INT_MIN` problem: because 2147483648 cannot be represented as an `int`, it gets promoted to `long` instead. That's why most definitions of `INT_MIN` use some oblique expression like `((-2147483647)-1)`. SPIRV-Cross will need to do the same for constants that happen to be the minimum representable signed value.

**Comment by ikryukov** [comment]
Thanks for the clarification. Is there any workaround for this?

**Comment by HansKristian-Work** [comment]
This should already be fixed on master.
