### ISSUE TITLE
Poorly generated GLSL when modifying matrix elements

### ISSUE THREAD

**Issue by prideout** [KhronosGroup/SPIRV-Cross#1938]
We (the Filament team at Google) have a shader pipeline that does GLSL => SPIRV => GLSL, and the latter step results in inefficient code in the following scenario:

```
void main() {
    mat4 mat = frameUniforms.clipFromWorldMatrix;
    mat4 rot;

    rot[0][0] = mat[0][0];
    rot[0][1] = mat[0][1];
    rot[0][2] = mat[0][2];
    rot[0][3] = mat[0][3];
    ...
}
```

The results of the round trip looks like this, which is obviously quite inefficient:

```
    mat4 _89 = _135;
    _89[0].x = frameUniforms.clipFromWorldMatrix[0].x;
    mat4 _92 = _89;
    _92[0].y = frameUniforms.clipFromWorldMatrix[0].y;
    mat4 _95 = _92;
    _95[0].z = frameUniforms.clipFromWorldMatrix[0].z;
    mat4 _98 = _95;
    _98[0].w = frameUniforms.clipFromWorldMatrix[0].w;
    mat4 _101 = _98;
    ...
```

The intermediate SPIRV contains sequences like the following, which is expected:

```
%36 = OpCompositeExtract %float %34 0 0
%89 = OpCompositeInsert %mat4v4float %36 %135 0 0
```

To repro, download [this gist](https://gist.github.com/prideout/8fd1da05cb8eb0aca61565cf6da286fc) and do:

```
glslc -std=310es -fshader-stage=vertex piecewise.glsl
spirv-opt -Os a.spv -o b.spv
spirv-cross b.spv
```

Some more context on the issue is at https://github.com/KhronosGroup/SPIRV-Tools/issues/4371.
@s-perron helped us narrow this down.
CC @pixelflinger

**Comment by s-perron** [comment]
> Is there evidence this results in bad codegen in ISA?

That is a fair question.

> The SPIR-V codegen is also bad. 

As mentioned in the spirv-opt issue, we could do something in spirv-opt, but it would not be as generally useful.  What if only two elements were inserted or the was some other intervening operation?  It is very common to have an OpCompositeInsert where you can reuse the same memory.  I don't know the spirv-cross code all that well, but it is conceivable that there is a check at the time the copy is added to determine if the same memory can be used.

If we can show that there are some drivers that do not optimize the generated code very well, I think it is reasonable to improve the generated code in spirv-cross.

**Comment by s-perron** [comment]
> Yes, and that's another case where RMW fails. The input SSA value can be reused.

I mentioned that this can only be done if the SSA value is not reused.  Thanks for calling it out here.  It was not mentioned in this discussion.  Even with that, it is common to do things like replace just the fourth element in a vector.  What you are suggesting for spirv-opt will not work in that case.  Because of the nature of SSA, spirv-opt cannot reuse the same "memory" or "registers" (however you think of the SSA values).

I can add something to replace a series of insert instruction with an OpCompositeConstruct, and that will help in many cases.  However it will not help in many cases.

> They would likely also fail optimizing the SPIR-V with OpCompositeInsert in that case.

Possibly.  HOwever, older OpenGL drivers would not expect this code pattern in the GLSL because nobody would write their code like this.  So it is possible that an OpenGL driver will not optimize this code well.  However, a Vulkan driver would see the OpCompositeInsert fairly often, so I would expect a Vulkan driver to handle it well.

**Comment by HansKristian-Work** [comment]
> So it is possible that an OpenGL driver will not optimize this code well.

Possible. If there is evidence of this being the case, we can consider doing the heroics to rewrite the Insert. There used to be subtle bugs in the past, which is why the current codegen is straight forward. These days there will be more subtle bugs to work through, especially due to the proper mediump/highp handling that requires aliased temporaries.

**Comment by s-perron** [comment]
That sounds reasonable.

**Comment by pixelflinger** [comment]
Actually the reason why we noticed this is because some nvidia drivers generate completely incorrect code -- that is, the output of our shader is garbage. And for us, we have no way to work this around.

**Comment by HansKristian-Work** [comment]
Sigh ... Well, I'll try to figure something out.

**Comment by s-perron** [comment]
FYI: https://github.com/KhronosGroup/SPIRV-Tools/pull/4802.  I don't think this will cover every case, but it does help with the TC that was provided.

**Comment by HansKristian-Work** [comment]
> FYI: [KhronosGroup/SPIRV-Tools#4802](https://github.com/KhronosGroup/SPIRV-Tools/pull/4802). I don't think this will cover every case, but it does help with the TC that was provided.

Thanks. That sounds like a very useful transform to have in general.
