### ISSUE TITLE
Support half precision in Metal shaders

### ISSUE THREAD

**Issue by cedega** [KhronosGroup/SPIRV-Cross#208]
Cross compiling to MSL seems to remove precision qualifiers specified in the source ESSL shader. For example, variables specified as "mediump float" should be translated as "half" in MSL.

For reference, using glslang to generate SPIR-V and then translating it back to ESSL using correctly retains precision qualifiers.

**Comment by billhollings** [comment]
The type qualifiers for MSL are driven by the size of the OpTypeFloat in the SPIR-V. MSL will output "half" floats when the size of a OpTypeFloat is 16 bits.Do you have a

**Comment by cedega** [comment]
I've attached a simple fragment shader with its compiled SPIR-V. I don't see an explicit 16-bit `OpTypeFloat`, but converting the SPIR-V to GLSL using:

`spirv-cross --version 300 --es frag.spv > converted_shader.glsl`

has the correct precision qualifiers.

[example.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/1096402/example.zip)

**Comment by billhollings** [comment]
The SPIR-V you submitted includes the `RelaxedPrecision` decoration on the variables. We may be able to use that to make the MSL type declarations output as `half` instead of `float`.

But I am a little wary of doing that across the board. According to the [SPIR-V spec](https://www.khronos.org/registry/spir-v/specs/1.0/SPIRV.html#_a_id_relaxedprecisionsection_a_relaxed_precision), the `RelaxedPrecision` decoration influences execution and calculations, but not the reading and writing (loading and storing) of values...which are still done as 32 bit values.

By contrast...declaring variables as `half` in MSL would read and write them as 16 bit values. This would be appropriate for an `OpTypeFloat 16`...which is what happens right now...but I'm not sure that a `RelaxedPrecision` decorations should have the same effect.

So...I'd like to discuss and get a consensus before making changes.

@HansKristian-ARM  If you have some background on this from the ESSL side, can you weigh in here, please?

1. Under what conditions would `OpTypeFloat 16` be explicitly generated as part of SPIR-V? Are there GLSL or ESSL shaders that would trigger that?
2. Should we be considering a `RelaxedPrecision` decoration to declare variables as 16 bit precisions..effectively overriding their `OpTypeFloat 32` declarations?
3. Should we treat this differently between `fragment` and `vertex` shaders?

**Comment by HansKristian-ARM** [comment]
RelaxedPrecision can apply to variables according to the spec, so it seems reasonable to make variables which are relaxed precision into half. This can get messy if implicit casting between half and float is not supported, because RelaxedPrecision escapes the type system (similar to the Read/Write decoration we recently added).

Storing something to a relaxed precision variable can narrow the precision, so that seems like a reasonable approach to me.

```
All loads and stores involving relaxed precision still read and write 32 bits of data, respectively. Floating-point data read or written in such a manner is written in full 32-bit floating-point format. However, a load or store might reduce the precision (as allowed by RelaxedPrecision) of the destination value.
```
The wording here means basically that the type itself is 32-bit for purposes of storage, so MSL should never use half in UBOs or SSBOs where binary layout matters, but for local variables and "logical" storage which does not expose the size of the variable, I think we are free to use half.

**Comment by billhollings** [comment]
I've been taking a stab at this by trying to swap out type names in type_to_glsl(), based on the ID of the object that is being operated on. It is turning out to be ugly and intrusive...and I have hit a real road block with constant declarations in shader `shaders-msl/frag/constant-array.frag`. The constants themselves are not marked with RelaxedPrecision. So...I'm not sure how to move forward.

@HansKristian-ARM...  I can submit my WIP code if someone wants to have a look at it. What's the best way to do that?

Other design options include:

- Replacing the SPIRType in any object that has relaxed precision with an invented SPIRType that looks like the original...but has it's width cut in half. This seems clean...except for SPIRType inheritance and decorations...which might get in the way. The lack of decoration on the constants described above will be a problem with this design too.

- See if we can get glslang and other tools to spit out real SPIRTypes with reduced widths for anything using relaxed precision. This would be the absolute cleanest design.

**Comment by HansKristian-ARM** [comment]
Not getting half on constants does not sound like an issue to me?

You can make a PR marked WIP in the PR message to make it clear it's WIP, and I can have a look at it.

Modifying SPIRType is not an option at least.

**Comment by billhollings** [comment]
The constants end up being declared as say `float4`...with vars that use those constants being declared as `half4`...and so we end up with issues where the var is assigned from the constant...or as in `shaders-msl/frag/constant-array.frag` where the var and constant are added together...and Metal complains.

To make a PR means I have to push my WIP to my own repo...which will end up polluting it's `master` until we get the issues resolved...if ever. And I want to be able to continue to contribute other PR's in the meantime.

I'm by no means a GIT expert...but that sounds like something I don't want to happen. How do people deal with that?

**Comment by HansKristian-ARM** [comment]
Hm, I think I'd need to have a look at the code to understand the problem.

The suggested way for this kind of "experimental" work is to push your work to a separate branch on your forked repo, then you can make a PR from your experimental branch to upstream master, that way you don't have to pollute your own master branch and you can keep doing PRs from your "clean" fork of SPIRV-Cross.

**Comment by billhollings** [comment]
I've posted PR #217 for this.

**Comment by HansKristian-ARM** [comment]
This didn't go anywhere and the correct solution will be explicit 16-bit types.
