### ISSUE TITLE
how do I decompile a shader with SPIRV-Cross?

### ISSUE THREAD

**Issue by gmmo** [KhronosGroup/SPIRV-Cross#2158]
Hello, I cloned the SPIRV-Cross repo and created a simple project to try to follow the readme.

https://github.com/KhronosGroup/SPIRV-Cross/blob/main/README.md

However, I don't get one simple thing.  When looking at the sample:

```
int main()
{
	// Read SPIR-V from disk or similar.
	std::vector<uint32_t> spirv_binary = load_spirv_file();

	spirv_cross::CompilerGLSL glsl(std::move(spirv_binary));
```

It expects and array of int32? I don't get this at all. Since it is a binary, I'd expect an array of bytes. I ended up loading my fragment shader as below (admittedly very "hackie")  I load as binary and copied the blob to a int32 pointer. Then divided the size by 4.

```
uint32_t* load_spirv_file(uint32_t* pBufferOut, size_t* pSize)
{
    std::ifstream ifd("tri.vert.spv", ios::binary | ios::ate);
    int size = ifd.tellg();
    ifd.seekg(0, std::ios::beg);
    std::vector<char> buffer;
    buffer.resize(size); // << resize not reserve
    ifd.read(buffer.data(), size);

    char* pBuffer = buffer.data();
    int buffSize = buffer.size();

    cout << "buffer size " << buffSize << std::endl;
    //std::vector<uint32_t> output(pBuffer, pBuffer + buffSize);

    pBufferOut = (uint32_t*)new char[buffSize];
    memcpy(pBufferOut, pBuffer, buffSize);

    *pSize = size / 4;

    return pBufferOut;
}
```

Then I tried a different constructor 

```
    uint32_t* spirv_binary = (uint32_t * )load_spirv_file(ir_, &word_count);
    spirv_cross::CompilerGLSL glsl(ir_, word_count);
    //spirv_cross::CompilerGLSL glsl(std::move(spirv_binary));
```

But it crashes. Can someone explain me with a sample how to decompile the attached fragment shader? I don't get it how this is done with the SPIRV-cross tools.

[tri.vert.zip](https://github.com/KhronosGroup/SPIRV-Cross/files/11594963/tri.vert.zip)

**Comment by cdavis5e** [comment]
> It expects and array of int32? I don't get this at all.

That's because SPIR-V binaries *are* arrays of int32. (See [§2.3](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#PhysicalLayout) and [§3](https://registry.khronos.org/SPIR-V/specs/unified1/SPIRV.html#_binary_form) of the SPIR-V specification for details.) The DXBC Tokenized Program Format, used in Direct3D 10-12, is the same way--in fact, it's probably part of the reason Khronos went with a 32-bit-wide ISA in the first place. (I'm aware that later D3D12 under SM6.x uses DXIL, which is a form of LLVM bitcode in a DXBC container. Which is ironic, when you consider that SPIR-V's predecessor was itself a form of LLVM bitcode.)

> But it crashes.

How? Does it throw a C++ exception? Which one?

> Can someone explain me with a sample how to decompile the attached fragment shader?

Umm... this is a vertex shader. Still, SPIRV-Cross shouldn't crash like that on a valid SPIR-V module...

...unless you got a bit confused and passed a pointer to an array that was never initialized (the `ir_` variable) to it. In the `load_spirv_file()` function, you discard the existing pointer that was passed and allocate a new array. Did you mean to pass `ir_` by reference, so that it would be updated by `load_spirv_file()`?

**Comment by gmmo** [comment]
Never mind, stupid bug on my end. Thanks for pointing it out. I should have called like this:

```
    uint32_t* spirv_binary = (uint32_t * )load_spirv_file(ir_, &word_count);
    printf("size = %d, blob = %x", (int)word_count, (int)spirv_binary);
    spirv_cross::CompilerGLSL glsl(spirv_binary, word_count);
```

I was able to decompile now on PC. thank you very much for the help.
