### ISSUE TITLE
Compilation errors on Linux due to macro conflict in Xlib.h

### ISSUE THREAD

**Issue by MattGuerrette** [KhronosGroup/SPIRV-Cross#22]
When building using SPIRV-Cross and Vulkan, if VK_USE_PLATFORM_XLIB_KHR is defined there is a macro conflict between spirv_common.hpp and X11/Xlib.h

The macro is defined as `#define Bool int` at line 82 in X11/Xlib.h
This conflicts with the Bool enum defined within spirv_common.hpp, this is a problem for those wishing to easily include spirv-cross and are using the Xlib surface creation with Vulkan.

**Comment by HansKristian-ARM** [comment]
I don't necessarily think strongly typed enums here would help. X11 headers are overriding something outside its namespace, so it would be impossible to refer to anything called "Bool" after X11 overrides that definition, even if it's strongly typed.

A workaround would be to use Boolean in SPIRV-Cross instead of Bool.

**Comment by MattGuerrette** [comment]
Thats true, strongly typed enums wouldn't solve it. Edited.
