### ISSUE TITLE
Overhaul HLSL row-major/column-major confusion

### ISSUE THREAD

**Issue by HansKristian-ARM** [KhronosGroup/SPIRV-Cross#295]
The HLSL backend is in need of some testing and validation that the matrix order is working as intended. We will likely need to actually test with a proper application for this.

**Comment by amerkoleci** [comment]
Note that D3DCompile has also option to specify the matrix order, but I think it can be handled by SPIRV-Cross also

**Comment by HansKristian-ARM** [comment]
SPIR-V can declare matrices in both row-major/column-major and so can HLSL, so SPIRV-Cross will need to handle both cases, also different layouts in the same file.

**Comment by HansKristian-ARM** [comment]
I believe this is more or less fixed, need to do some extra testing to close this.

**Comment by BartmanAbyss** [comment]
It seems CompilerHLSL::layout_for_member should always output a matrix decoration, even if not in block interfaces.
We had the following GLSL->SPIRV code
`
struct ShadowMap {
   matrix lightMtx;
   ...
};

uniform Light {
  matrix modelMtx;
   ...
  ShadowMap shadows[6];
}`
where SPIRV-Cross would only add `row_major` decoration to `Light.modelMtx`, but not to `ShadowMap.lightMtx`

I commented out that check, and it seems to work, however I'm not 100% sure if that's the right thing to do...

**Comment by sgorsten** [comment]
Thank you for your hard work maintaining this library!

I wanted to let you know that this issue tripped me up when writing a Direct3D 11 renderer for a small project I'm working on. In my case, the "matrix multiplication order inversion" behavior that SPIRV-Cross applies when generating HLSL was unhelpful and took me a little while to figure out. My engine stores matrices in column major order, and I memcpy CPU-side objects directly into mapped uniform/constant buffers, and my GLSL shader code uses (matrix * vector) multiplication order. This works for OpenGL and Vulkan, but I was surprised when I was getting garbage from my Direct3D backend, which I eventually tracked down to the `emit_binary_func_op(ops[0], ops[1], ops[3], ops[2], "mul");` lines in spirv_hlsl.cpp. It seems you also have logic to reverse the row_major/column_major annotations if any are present.

I don't have the full context for why the inversion functionality was added (earlier D3D APIs, perhaps?), but would it be possible to have this behavior controlled by a flag in the CompilerHLSL::Options struct, rather than being unconditionally applied? In my case, the architecture of my engine and shader framework is actually simpler without the inversion behavior, as column major storage and mul(matrix, vector) multiplication order work just fine with my D3D backend.

I'd be happy to submit a pull request if it would be helpful.

**Comment by msiglreith** [comment]
Bump regarding the previous comment https://github.com/KhronosGroup/SPIRV-Cross/issues/295#issuecomment-351706750

Is it safe to remove the mentioned condition? Hitting a similar case as above. IMO it looks safe at least in the case of matrix layout as they doesn't appear to he inherited of upper structures or something similar afaik. https://github.com/KhronosGroup/SPIRV-Cross/blob/d93807a62506b564a7c583842ebbe047f8705b42/spirv_hlsl.cpp#L1748-L1766

**Comment by HansKristian-ARM** [comment]
For HLSL, it makes sense to remove the condition iff:
- The row layout qualifier does not change how matrix construction or access works. E.g. creating a value type with row_major qualifier (like a struct on the stack) should not affect code-gen unless it's being used in a buffer.

If that'd work, we could have a "backend.supports_matrix_order_in_substructs" or something like that.

**Comment by msiglreith** [comment]
Thanks for the details! I'll try to look into this and setup a PR.
What would be the purpose of `backend.supports_matrix_order_in_substructs`?

**Comment by HansKristian-ARM** [comment]
Well, actually ... layout_for_member is overridden in HLSL, so probably just change the implementation there. Just make sure all structs are treated with the row_major/col_major declaration.

**Comment by mellinoe** [comment]
@HansKristian-ARM Not sure if I should file something separately, but I'm seeing an issue with the generated code in one of my HLSL shaders. It seems that `row_major` is being attached to a custom struct, which is not valid, but not to the matrices contained in that struct.

```
struct Veldrid_NeoDemo_Objects_WorldAndInverse
{
    float4x4 World;
    float4x4 InverseWorld;
};

cbuffer _23 : register(b9)
{
    row_major Veldrid_NeoDemo_Objects_WorldAndInverse _23_field_WorldAndInverse : packoffset(c0);
};
```

> (29,5-53): error X3077: non-matrix types cannot be declared 'row_major' or 'column_major'

**Comment by HansKristian-ARM** [comment]
Ye, this is the same issue I think. I'll prioritize getting this fixed asap.

**Comment by mellinoe** [comment]
@HansKristian-ARM Thanks for the quick fix. I updated and everything seems to be working as expected now.
