### ISSUE TITLE
Map from original to transformed entry point names

### ISSUE THREAD

**Issue by grovesNL** [KhronosGroup/SPIRV-Cross#316]
Currently entry points may be transformed during compilation, but it's not obvious how to determine whether a transformation has occurred.

For example, if a default entry point is defined as `main` (which is quite common), the [MSL output will rename it to `main0`](https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_msl.cpp#L63) because `main` is not allowed in MSL. That behavior seems reasonable, but how can we determine that this renaming occurred in order to use the transformed name when configuring Metal shaders?

More generally, for any of the compilers, if a function named has been transformed (i.e. because it is reserved in that SL or some other issue), how can we map from the original entry point names to the transformed entry point names?

Perhaps it's as straightforward as creating and exposing a map prior to the compile step (i.e. during the constructor). Although maybe it's possible that some dynamic renaming would need to occur during compile in the future, in which case we wouldn't be able to do this. Let me know what you think.

**Comment by HansKristian-ARM** [comment]
Setting an entry point name is something I think could already work.
It shouldn't be that much work to add a way to change the name of an entry point during reflection. This name should be used somehow during compilation (except on GLSL of course, because it only understands main()). I don't think this is happening at the moment given that MSL hardcodes the main -> main0 transform, but sounds trivial to make this more generic.

Of course there are issues with "main" as an entry point name as it is reserved, I think the easiest way there is just to say it is reserved and it will be called something else.

From an API perspective something like:
```
Compiler::rename_entry_point(from, to);
```
should be good enough, really.

**Comment by grovesNL** [comment]
@HansKristian-ARM That sounds good to me!

It would be useful to either have 1) a list of reserved entry point names for each compiler so we can explicitly set a new name (i.e. so we know `to` is not reserved), or 2) for the current approach, a way to know whether it was renamed automatically by the compiler.

Being able to know all reserved names is not too important anyway. Applications could use `rename_entry_point` to automatically prefix all entry points with some random characters to avoid reserved words.

**Comment by billhollings** [comment]
I'm not sure what the problem is that is trying to be fixed here. Can you clarify, please?

Currently MSL requirements force a renaming of `main()` to something else. Somewhat arbitrarily, I chose `main0(...)`.

As far as an app knowing how the compiler renames entry points...for MSL, the rules are basically...

1. `main` is converted to `main0`.
2. All other entry point names are left alone.

Do we have a use case for a more general need for more flexible renaming requirements?

BTW...I am about to issue a PR that includes some changes to how the name is changed (but not to the name itself). So...please hold off for a couple of days before anyone takes a stab at generalizing.

**Comment by grovesNL** [comment]
@billhollings The rules are fine. I'm looking for a way to know that my `main` has been renamed to `main0` without leaking the renaming rules into my application.

For example, if there are similar rules in the other compilers (now or in the future), I'd prefer to query the final entry point names.

Otherwise, what @HansKristian-ARM is proposing, is that I just rename each of the entry point names myself. Either being able to query the updated name, or renaming the entry points (i.e. so I could prefix each name), would work well.

**Comment by billhollings** [comment]
Hmmm...it seems to me that having the app pass in an entry point name change mapping (i.e. `main` -> `myMain`) sounds like the app would have to know only to do that only for Metal (because as @HansKristian-ARM points out...you'd have to NOT do this for GLSL). In which case...you're stuck with platform-specific app code no better than simply knowing to use `main0` in Metal.

And...unless I'm missing something...it doesn't sound like there are any other general purpose use-cases for a general-purpose renaming mechanism.

Would your query idea...simply retrieving a list of the entry point names be useful?

If so...there is already an existing `get_entry_points()` function. Does that suffice?

If that would suit your needs...`get_entry_points()` might not work correctly now because of the way renaming happens. But the renaming updates that I mentioned I'm about to PR should allow that to work after compilation is complete.

**Comment by grovesNL** [comment]
Exactly, that's the idea. I would like to avoid special casing MSL if possible.

`get_entry_points` is the correct concept but I need to know the map from the original name to the renamed value, as you said. So it's more like `get_entry_points` would return a map containing pairs of original name/cleaned name.

**Comment by billhollings** [comment]
Okay. Got it.

Perhaps I can just jam a simple `get_cleansed_entry_points()` function into the PR I am preparing right now.

**Comment by billhollings** [comment]
PR #321 includes this as a new feature.

**Comment by grovesNL** [comment]
Great, thanks!

**Comment by HansKristian-ARM** [comment]
This should be resolved now.
