### ISSUE TITLE
Add options to flip texture op Y coordinate in GLSL

### ISSUE THREAD

**Issue by Kangz** [KhronosGroup/SPIRV-Cross#322]
Background: In NXT we're having an issue related to the fact that texture coordinates in OpenGL start from the bottom-left instead of top-left like in other APIs. This is a problem especially when copying from buffers to textures (and vice-versa) because the NXT applications assume a top-left origin. To fix this with the best perf we are looking at storing textures flipped and make use a new option in addition to vertex.flip_y.

Would it be possible to add an option to CompilerGLSL to make all texture coordinate arguments to builtins have their Y coordinate flipped (as in 1.0 - y or width - y)?

**Comment by HansKristian-ARM** [comment]
Textures in GL are not "bottom-left" or "top-left". This only manifests itself when rendering it to the backbuffer if you map clip coords to texture coords 1:1, which is the only instance where "bottom-left" and "top-left" has any meaning. The first pixel you put into texture updating functions is coordinate (0, 0), which is the case for all APIs, and UV (0, 0) on its own has no meaning.

Flipping texture coords is a brittle way of doing things and I do not want to support this, because there are always better solutions. Flipping texture coords becomes extremely messy because you typically start to need different behavior for different textures (FBO vs uploaded textures), and this breaks down very quickly.

Generally, the way to go is flipping vertex Y if anything.

**Comment by Kangz** [comment]
I had somehow convinced myself that buffer <-> texture copies were Y-flipped in GL compared to other APIs. But it is wrong, so like you're saying, flipping vertex Y should be enough.
