### ISSUE TITLE
GLSL to ES exception: Cannot flatten struct inside structs in I/O variables.

### ISSUE THREAD

**Issue by thatname** [KhronosGroup/SPIRV-Cross#351]
When cross-compiling the following shader to GLSL es 1.00, SPIRV-Cross throws an exception
which says: "Cannot flatten struct inside structs in I/O variables."

#version 450
struct VertexAttributes
{
	vec3 VertexColor ;
};

in vec3 VertexColor;

out vertexToFragment
{
	VertexAttributes attr;
} vertexOut;

in vertexToFragment
{
	VertexAttributes attr;	
} fragmentIn;

void entry_vert()
{
	vertexOut.attr.VertexColor = VertexColor;
}

out vec3 fragColor;
void entry_frag()
{
	fragColor = fragmentIn.attr.VertexColor;
}

Whereas cross-compiling it to desktop glsl, there is another issue: The shader has 2 interface blocks with exact same name but different storage qualifiers. Instead of output the names as is, SPIRV-Cross changed one of them, from "vertexToFragment" to "_24".

**Comment by HansKristian-ARM** [comment]
The "cannot flatten" thing is there because SPIRV-Cross currently does not support flattening structs recursively.

The second case happens because SPIRV-Cross needs to be careful emitting duplicate names (legal in SPIR-V, but not in GLSL). However, if GLSL supports duplicate names as long as they are in different storage qualifiers, SPIRV-Cross currently does not take that into account.
