### ISSUE TITLE
Reflection is wrong in the presence of a multiple structured buffer/appendbuffer

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#456]
On latest glslang and spirvcross, a very simple shader like the following:

```hlsl
RWStructuredBuffer<float4> g_RWStructuredBuffer : register(t0);
AppendStructuredBuffer<float4> g_AppendBuffer : register(t1);

float4 main(float4 input : TEXCOORD0) : SV_Target0
{
	g_AppendBuffer.Append(input);
	g_RWStructuredBuffer[0] = input;
	return float4(0,0,0,0);
}
```

returns wrong reflection information. The storage_buffers vector reports having 3 members (which is correct), but they're named g_AppendBuffer, g_AppendBuffer_count and g_AppendBuffer. However if I compile the shader it comes out correctly. Likewise, if I have two RWStructuredBuffers they're also reported incorrectly.

**Comment by HansKristian-ARM** [comment]
This is intentional. HLSL has an awkward scheme where it creates SSBOs out of nowhere to deal with the magic "atomic counters" inside the buffers. See:

https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_cross.hpp#L398
https://github.com/KhronosGroup/SPIRV-Cross/blob/master/spirv_cross.hpp#L405
as a way to workaround this.

**Comment by redorav** [comment]
Sorry, I'm not quite sure I understand. There are only two buffers, and reflection is telling me there are 3 because one of them is _count for the append buffer. That much I think I get based on what you just said.

> HLSL has an awkward scheme where it creates SSBOs out of nowhere to deal with the magic "atomic counters" inside the buffers

However, what I'm reporting as bug is that there is also a structured buffer there as well (g_RWStructuredBuffer) which has disappeared from the reflection information and been renamed g_AppendBuffer.

So, where I would expect
1) g_AppendBuffer
2) g_AppendBuffer_count
3) g_RWStructuredBuffer

I'm instead getting

1) g_AppendBuffer
2) g_AppendBuffer_count
3) **g_AppendBuffer**

which I think is wrong.

**Comment by HansKristian-ARM** [comment]
Oh right ... yes, that is likely because HLSL also likes to reuse the same block type for all its buffers, which makes the reflection output a bit weird. There's an issue here: https://github.com/KhronosGroup/SPIRV-Cross/issues/195 which is probably what you are referring to. I still haven't figured out a clean solution which makes sense in all cases.

One workaround is to look at compiler.get_name(res.id) rather than the res.name for SSBOs. res.name follows the GLSL convention where it is the block name which is significant and not the instance name.

**Comment by redorav** [comment]
Ok, compiler.get_name() did the trick for me. I suppose if you have a bug for this already you can close this. Thanks for the quick reply!
