### ISSUE TITLE
HLSL: Flatten arrays inside push constant blocks

### ISSUE THREAD

**Issue by msiglreith** [KhronosGroup/SPIRV-Cross#458]
Root constants in HLSL don't allow arrays inside constant buffers (https://msdn.microsoft.com/de-de/library/windows/desktop/dn899219(v=vs.85).aspx):

> Arrays are not permitted in constant buffers that get mapped onto root constants since dynamic indexing in the root signature space is not supported. For example, it is invalid to have an entry in the constant buffer like float myArray[2];

A workaround would be flattening the variables inside the block I guess.
Example shader: https://github.com/SaschaWillems/Vulkan/blob/master/data/shaders/pushconstants/lights.vert#L20

**Comment by HansKristian-ARM** [comment]
Uh ... How do you expect this to work? Vulkan allows you to have arrays in push constant blocks, but the access must be dynamically uniform (probably so push constant reads can use scalar registers always).

The only thing you can flatten in a reasonable way would be constant-index arrays, but that doesn't seem very useful.

This seems more like a portability hazard where arrays in push constant blocks simply need to be banned, or the D3D12 backend would just have to make the push constant block into a classic cbuffer instead in those cases.

**Comment by msiglreith** [comment]
Thanks for the reply!
An inline cbuffer descriptor seems to be a good idea for handling the case with arrays. Flattening would then be only an optimization for static indexing as root constants seem to have a bit better performance than inlined descriptors.

**Comment by HansKristian-ARM** [comment]
Array flattening gets gnarly very quickly. Array of structs, arrays of arrays, etc, are all very annoying to deal with in any sensible way and would require even more complex handling deep down. Due to the large complexity in supporting this "optimization" for questionable gains in practice, I would prefer to avoid it if possible. Any use of arrays should be moved out to a cbuffer.

Arrays with constant indices should be optimized out at a higher level, imo. SPIRV-Cross is not an optimizer.

**Comment by msiglreith** [comment]
Understood, fair enough!
Closing this as something to tackle on my side (:
