### ISSUE TITLE
Spirv-Cross slow for load time reflection

### ISSUE THREAD

**Issue by redorav** [KhronosGroup/SPIRV-Cross#725]
We've been integrating spirv-cross for actual Vulkan work in the engine. In the past we've used spirv-cross as a way to obtain reflection information to produce glsl output so it was an offline process. Now that we're loading spir-v in, we want to use spirv-cross to get the shader resources at load time. However, we've observed that spirv-cross is slow to the point of not usable at load time and we're considering doing it as an offline process and have our own metadata. This is clearly undesirable though, and we'd like to avoid it. My gut feeling is that simply reading data from the binary shouldn't be too expensive so the call to spirv_cross::Compile must be doing a lot of extra work. Could you please advise on the best solution here? Thanks!

**Comment by HansKristian-ARM** [comment]
I need more information. How slow is slow? How does it compare to building actual pipelines? How fast do you expect it to be? Which SPIR-V modules did you test with?

**Comment by redorav** [comment]
We have two code paths. One that uses SPIRVCross to load reflection data from the SPIRV directly and another that uses custom code to load reflection data that we extracted offline and wrote into a custom binary header that we put in front of the SPIRV data.

Executing shader reflection parsing on 500 pairs of vertex and pixel shaders gives these timings.

  Custom Reflection = 0.01 seconds
  SPIRVCross Reflection = 12.14 seconds.

These are collected from a PC debug build of our game, though in this context the SPIRVCross library was built with optimizations enabled (/O2). 

We are launching our game with a debugger attached, meaning the Windows debug heap is enabled. Also note that our SPIRV is optimized and debug data has for the most part been removed.

**Comment by HansKristian-ARM** [comment]
That's about 24 ms per shader pair, which sounds like very sketchy.

There's generally a lot of heap allocations, so there could be a freak case with the debug heap? What happens if you use a proper heap?

For reference, I tried hacking up main.cpp to call the constructor in a loop with a test shader of 5.5 kB (`glslangValidator -H -V -o test.spv shaders/tese/water_tess.tese`) (has debug info so lots of string allocation and so on). 1 Compiler construction from SPIR-V, including SPIR-V parsing takes 28 microseconds (of course, this is with warm caches, but still). That's 3 orders of magnitude faster than your numbers. This is on Linux with optimizations. In a debug -O0 build I get 200 microseconds per constructor, but still no-where near this slow.

**Comment by redorav** [comment]
Disabling the debug heap (start without debugging in Visual Studio) gives these numbers:

0.03 seconds vs 20.01 seconds

Perhaps a bit more detail on how we use the library. We grab the incoming spirv and create a compiler object for them as normal so

spirv_cross::Compiler compiler(spirv);

and then we cache the resources using

compiler.get_shader_resources()

Then for every resource we want to look for we search in the resources. It's worth noting that these numbers are just for the instantiation of the spirv_cross::Compiler object, and we haven't timed the rest which adds even more cost on top.

**Comment by HansKristian-ARM** [comment]
Sure, I just measured with instantiating with the Compiler object as well, but it's fairly obvious what the culprit is now (1000x slowdown, wow? o_O). Sounds like this is your real issue, not SPIRV-Cross per-se.

**Comment by redorav** [comment]
When you say it's fairly obvious what the culprit is, do you mean it's the debug heap? I can't realistically disable the debug heap for programmers here to be able to run spirv_cross.

**Comment by HansKristian-ARM** [comment]
Yes, the debug heap (or some other debug mechanism) is clearly the culprit here. Is it possible to temporarily disable it ala https://msdn.microsoft.com/en-us/library/5at7yxcs.aspx? (No idea if it does what you need).

I don't know anything about the debug heap, so the two first suggestions I got from talking with others was:
- Is _CRTDBG_CHECK_ALWAYS_DF set?
- Is Appverifier running for some reason?

I assume you just need debug heap to debug your code, not SPIRV-Cross', which runs clean in Valgrind.

**Comment by redorav** [comment]
The debug heap issue is just a side effect of linking the static library against our main executable, we don't really need to verify that SPIRV-Cross is good.

I've been asking around here and it seems like we also have these kinds of issues with DX11 reflection libraries on PC where debug build compilation is really sluggish due to this, as external libraries don't go through our memory manager. I think the decision is going to be to go with our own system and by the looks of it, it may have been desirable even for DX11, because we're not in a position to disable the debug heap.

Thanks for all your input as it has been very helpful. We'll still use SPIRV-Cross in the shader compiler for sure, but I think the runtime information will have to be a simple binary header at the top of every shader.

**Comment by HansKristian-ARM** [comment]
Fair enough. Don't think there is anything to do for me here now, so closing.
