### ISSUE TITLE
Glsl backend emits all resources and structs instead of only ones used by an entry point

### ISSUE THREAD

**Issue by jodavis42** [KhronosGroup/SPIRV-Cross#727]
Quick explanation of what I'm trying to do to give context. I'm running into issues with the optimizer and spirv-cross being slow in debug mode (mostly due to stl iterator debugging) so I'm experimenting with ways to make this faster. Part of this our application generating a ton of un-used permutations, but I'm trying to see what I can do independently of this.

The current test I was running was to utilize multiple entry points so I could optimize one "library" of all shaders instead of each individual shader. Independently of the optimizer's performance here, I noticed that when running spirv-cross on one entry point it emits all resources and all classes in the library. This causes two major problems, one is that's it can be quite slow in debug to emit the string containing all of these. The other is that some resources are invalid.

In the attached file I ran spirv-cross on entry point 5 which is a vertex shader. This ends up outputting unused input blocks, but these are illegal in vertex shaders. I also attached the resultant glsl from this.

Potentially I could trim down the spirv to one entry point, but I didn't see a an option on the optimizer or a tool in spirv-tools to do this.

[LibraryTest_Glsl_EntryPoint5.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/2487981/LibraryTest_Glsl_EntryPoint5.txt)

[LibraryTestOptimized.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/2487960/LibraryTestOptimized.txt)

**Comment by HansKristian-ARM** [comment]
I tried EntryPoint5.txt but this is a fragment shader, not a vertex shader.

One type of resource that we must honor is the input/output declaration for the entry point, but this seems to work fine. E.g., for the fragment entry point we have:

```
               OpEntryPoint Fragment %37 "EntryPoint_Main_5" %38 %39
```
Only input/output resources %38 and %39 are declared in the output GLSL, so this works fine.

The other consideration is that all buffer blocks, and resources are emitted. This can indeed be a problem, especially if there are resource types which can't work in the stage you're emitting for.
There is a mechanism to purge all unused variables however, try `--remove-unused-variables`, or the API equivalent. The only resources left are:

```
layout(binding = 0, std430) buffer RuntimeArray_Real4_Buffer
{
    vec4 Data[];
} Colors_RayTracePixel;

layout(binding = 4, std140) uniform RayTracer_PixelMaterial
{
    ivec2 Size_RayTracePixel;
} Material;

layout(location = 0) in RayTracer_PixelIn
{
    vec2 Uv;
} In;

layout(location = 0) out RayTracer_PixelOut Out;
```
and these are all used by this entry point, so seems to work fine. Using this option for multiple entry point SPIR-V makes sense to avoid problems like these I guess. Not sure if I should just force it on for cases like these ...

The last problem is all the structs being declared, which are not used. This shouldn't affect correctness, but bloats the output. There is no solution for that currently. Analyzing which struct types are statically used is possible, but it's very fiddly since struct type dependencies are more subtle than just looking at statically used variables. SPIRV-Tools might already have some passes to create optimized, stripped down SPIR-V based on a single entry point already, and I would like to avoid duplicating the effort of SPIRV-Tools if I can.

As for STL iterator debugging, do you need that for SPIRV-Cross? I've seen a similar complaint recently with debug heaps because SPIRV-Cross was baked into the main executable and built with full debug enabled. Would you be able to avoid this altogether if SPIRV-Cross had a C API / dynamic library option? It's on the radar, but more motivation for it would bump the priority up.

**Comment by jodavis42** [comment]
It seems I had made a small typo when editing the entry point names. The variable %EntryPoint_Main_5 didn't have the name "EntryPoint_Main_5" because I got off one line. Manually editing spirv disassembly for testing makes it easy to make mistakes.

Here's an update one just in cast, but this seems to be working correctly as you mentioned, especially with --remove-unused-variables.
[LibraryTestOptimized.txt](https://github.com/KhronosGroup/SPIRV-Cross/files/2496194/LibraryTestOptimized.txt)

I'll poke at the optimizer a bit more / ask them if there is a pass to do this.

I don't need iterator debugging for spirv-cross, but unfortunately some other static libraries we use have this on which causes mis-matched settings and then linker errors happen. Changing these other libraries might be a lot of work so I'm seeing what I can do here first.

To deal with this same problem for the optimizer I was attempting to use the C API so I could run a release dll (this required me writing a bit of the api for the optimizer myself). A similar api for spirv-cross would help a lot. We interface with spirv-cross much more heavily than with the optimizer (remapping names, extracting reflection, and a few other things due to our current graphics api usage) so this wasn't something I saw as being easy to do myself.

**Comment by HansKristian-ARM** [comment]
Right, so the conclusion is that the static-only nature makes debugging with SPIRV-Cross hard/painful because debug STL makes anything you do brutally slow, and SPIRV-Cross needs to use STL quite a lot, especially unordered_map/set.

I think the forward looking thing is to work on a solid C ABI for SPIRV-Cross so you can link to a release DLL instead and not bothering with performance issues in SPIRV-Cross. This will help other uses as well.

**Comment by HansKristian-ARM** [comment]
There doesn't seem to be a real bug here, but rather a performance related problem in a debug scenario on MSVC, so closing. There is no obvious action to take right now.

The C API implementation is captured in https://github.com/KhronosGroup/SPIRV-Cross/issues/611.
