### ISSUE TITLE
invariant qualifier is preserved but not honored

### ISSUE THREAD

**Issue by prideout** [KhronosGroup/SPIRV-Cross#761]
We have a depth-pass SPIRV shader and a color-pass SPIRV shader that compute an invariant `gl_Position` in the same way. After transpiling back to GLSL, the color shader uses an intermediary variable to compute position, but the depth shader does not. This causes variance, which in turn leads to depth artifacts.

I've added our two SPIRV shaders to `shaders/asm/vert` in [this commit](https://github.com/prideout/SPIRV-Cross/commit/352eb27). This issue can likely be provoked with much simpler shaders, but I thought it best to provide the originals.

To repro, merge the above commit (or copy the two files manually), then do:

```
./test_shaders.py shaders/asm/vert
cd shaders/asm/reference/vert
grep gl_Position invariant-depthpass.asm.vert # <== no intermediary variables
grep gl_Position invariant-colorpass.asm.vert # <== uses _82 intermediary
```

**Comment by prideout** [comment]
One more note: in the two SPIR-V files that I added, the invariant expression can be found by examining the data flow for the last `OpMatrixTimesVector` instruction in both cases.

**Comment by HansKristian-ARM** [comment]
Hm, this one is rather difficult. I'm not 100% sure if this is a SPIRV-Cross bug or GLSL compiler bug.

The invariant statement is emitted, as you say the only difference is that the expression is split up by having part of it go to a temporary. The split to temporary happens because of multiple uses of the same expression, which does not happen in the depth-only shader.

GLSL 450 says something like:


To guarantee invariance of a particular output variable across two programs, the following must also be
true:
- The output variable is declared as invariant in both programs.
- The same values must be input to all shader input variables consumed by expressions and flow control
contributing to the value assigned to the output variable.
- The texture formats, texel values, and texture filtering are set the same way for any texture function
calls contributing to the value of the output variable.
- All input values are all operated on in the same way. All operations in the consuming expressions and any intermediate expressions must be the same, with the same order of operands and same associativity, to give the same order of evaluation. **Intermediate variables and functions must be declared as the same type with the same explicit or implicit precision qualifiers.** Any control flow affecting the output value must be the same, and any expressions consumed to determine this control flow must also follow these invariance rules.
- All the data flow and control flow leading to setting the invariant output variable reside in a single compilation unit

I don't see it explicitly calling out that the invariant shaders must use the exact intermediate variables, but maybe that's the rule.

**Comment by HansKristian-ARM** [comment]
Asked around, apparently this is a bug. This will take a while to fix.

**Comment by prideout** [comment]
Understood, thanks for looking into this!  To answer your earlier question, we see invariance on Pixelbooks with Intel HD Graphics 615.

(As a side note, we happen to be using WebGL in our test, which we realize adds a layer of shader munging.  However, experimentation has shown that the depth artifacts are indeed caused by the intermediate variable mismatch that I described earlier.)

**Comment by HansKristian-ARM** [comment]
I've got a candidate PR here which should fix the issue: https://github.com/KhronosGroup/SPIRV-Cross/pull/769 please test it and report if it fixes your issues on that GPU.
