### ISSUE TITLE
integrate spirv-tools validation

### ISSUE THREAD

**Issue by fjhenigman** [KhronosGroup/SPIRV-Cross#766]
Call the spirv-tools validator before proceeding into spirv-cross.
This means parsing twice, once in the spirv-tools validator and again in spirv-cross, but that will be fixed when spirv-cross uses the spirv-tools parser, see #765.

**Comment by fjhenigman** [comment]
I'm not sure we want validation on by default.  For one thing, whatever default we choose now may not suit everyone and will eventually become outdated.
Also do we want to be able to run spirv-cross on invalid input, e.g. for testing?

I tried running the tests with validation on, and in the "spv1.3" environment I get these validation failures:

shaders/flatten/multi-dimensional.desktop.invalid.flatten_dim.frag
shaders-hlsl/frag/constant-buffer-array.invalid.sm51.frag
> Only a single level of array is allowed for descriptor set variables

shaders-msl/frag/shadow-compare-global-alias.invalid.frag
> OpFunctionCall Argument <id> '35[uTex]'s type does not match Function <id> '17's parameter type.

shaders-msl/frag/shadow-compare-global-alias.invalid.frag
> OpLoad Result Type <id> '16' does not match Pointer <id> '35[uTex]'s type.

shaders-msl/asm/comp/buffer-write-relative-addr.asm.comp
shaders-msl/flatten/rowmajor.flatten.vert
> Structure id 7 decorated as BufferBlock for variable in Uniform storage class must follow standard storage buffer layout rules: member 1 at offset 4 is not aligned to 16

If those are just problems in the tests I'll fix those, then we could make spv1.3 validation the default.
In the vulkan1.1 environment there are more failing shaders.  I see the first three validation errors above, not the fourth one, and a couple new ones.

**Comment by dj2** [comment]
We do want validation on, otherwise we have to make all kinds of assumptions in the parsing and execution code to handle invalid SPRIV. With validation on we know the incoming data is valid. We should never receive invalid shaders internally.

Having a flag to turn it off is fine, but default should be on I believe.

**Comment by fjhenigman** [comment]
Any input @HansKristian-ARM ?  Thanks.

**Comment by cdavis5e** [comment]
The test suite actually runs `spirv-val` on SPIR-V modules before feeding them to the `spirv-cross` tool, under the `vulkan1.1` environment. The ones that have "invalid" in the filename are the ones known to fail validation under `vulkan1.1`--perhaps because they need an extension that may not be available on an unextended Vulkan 1.1 implementation; or because they *used* to validate, but when @HansKristian-ARM updated SPIRV-Tools, they stopped. (Maybe the ones in the latter group need to be fixed.) That should hopefully explain the results you're seeing.

**Comment by fjhenigman** [comment]
> The test suite actually runs `spirv-val` on SPIR-V modules before feeding them to the `spirv-cross` tool, 

I see this in the test script (paraphrasing):
`if 'invalid' not in shader name: run spirv-val`
sometimes before spirv-cross, sometimes after it, but in all cases it always runs spirv-cross, whether the shader is 'invalid' or not.
I think the script would halt if spirv-val failed, hence it isn't run on 'invalid' shaders.

I guess the thing to do is turn off spirv-cross validation for 'invalid' shaders.  (That was my first idea but I wasn't sure what 'invalid' meant exactly.)  Then take out the calls to spirv-val in the test runner.
Sound right?

**Comment by cdavis5e** [comment]
Yeah, that sounds about right to me.

**Comment by HansKristian-ARM** [comment]
Could you elaborate what the goal of this issue is? The way I read the first post is integrating spirv-tools as a dependency and run spirv-val before parsing SPIR-V in the SPIRV-Cross library, but the discussion afterwards seems to concern itself with test_shaders.py.

The story of .invalid. in test_shaders.py is as @cdavis5e says, it's to workaround when I run into issues with spirv-val, spirv-opt or glslang which causes working SPIR-V to fail validation. Usually I get a few new failures when updating SPIRV-Tools or glslang. I usually report those issues when I get around to it, but it's a pragmatic workaround more than anything. The main reason to run spirv-val in testing is to make sure I don't end up spending time fixing bugs for invalid SPIR-V, and it's a useful sanity check for the SPIR-V asm tests. There should be a sweep of the current .invalid. files to see if the issues have been resolved in latest SPIRV-Tools so we can un-invalidate them in spirv-val testing.

**Comment by fjhenigman** [comment]
>  The way I read the first post is integrating spirv-tools as a dependency and run spirv-val before parsing SPIR-V in the SPIRV-Cross library, but the discussion afterwards seems to concern itself with test_shaders.py.

That's the goal.  The discussion around testing was to help me figure out how to make the tests pass after achieving the goal.  spirv-cross with validation added complained of course on the .invalid. cases and I didn't know at first what was going on.

> There are also a few corner cases where the SPIR-V is technically invalid in VK 1.1 environment but it still flexes certain corner cases in the implementation which is useful to test, but I don't remember right now which shaders do that.

We'll need to know which shaders want a different environment, perhaps something in the name (similar to the .invalid. idea) or something in the path (e.g. group them into a folder) so we can invoke spirv-cross with a flag that specifies the proper environment.  There don't seem to be any right now outside of the .invalid. set which fail to validate in Vulkan 1.1 environment.

**Comment by HansKristian-ARM** [comment]
As agreed in https://github.com/KhronosGroup/SPIRV-Cross/pull/767, this integration work will be done outside SPIRV-Cross' codebase.
