### ISSUE TITLE
ensure_correct_attribute_type() does not preserve pointer-type qualifiers.

### ISSUE THREAD

**Issue by HansKristian-Work** [KhronosGroup/SPIRV-Cross#853]
Found issue during review of: https://github.com/KhronosGroup/SPIRV-Cross/pull/852

**Comment by cdavis5e** [comment]
In fact it does, *if* the passed-in type is a pointer. (See [here](https://github.com/KhronosGroup/SPIRV-Cross/blob/d9ed3dcc7a7e62e5f95fd8f24e3d35e7e402ae92/spirv_msl.cpp#L1604) and [here](https://github.com/KhronosGroup/SPIRV-Cross/blob/d9ed3dcc7a7e62e5f95fd8f24e3d35e7e402ae92/spirv_msl.cpp#L1634).) The problem was that the change in #852 stopped passing the original pointer type to this function.

**Comment by HansKristian-Work** [comment]
Oh. Maybe it was my bug then :disappointed: , either way, it's a bug.
